d3.select('body')
	.append('svg')
		.attr('width', 400)
		.attr('height', 400)
		.style('background', '#ccc')
	.append('rect')
		.attr('width', 300)
		.attr('height', 300)
		.attr('x', 50)
		.attr('y', 50)
		.style('fill', '#ff0000')
d3.select('svg')
	.append('circle')
		.attr('cx', 300)
		.attr('cy', 300)
		.attr('r', 40)
		.style('fill', '#ccc')